"""add_audit_columns_indexes_is_active

Revision ID: 89d64041c7f0
Revises: 001_initial_schema
Create Date: 2026-04-27 14:09:47.115359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89d64041c7f0"
down_revision: Union[str, None] = "001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emprestimo",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "emprestimo",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_emprestimo_data_devolucao_esperada"),
        "emprestimo",
        ["data_devolucao_esperada"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emprestimo_status"), "emprestimo", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_emprestimo_usuario_id"), "emprestimo", ["usuario_id"], unique=False
    )
    op.add_column(
        "pessoa",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "pessoa",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_pessoa_usuario_id"), "pessoa", ["usuario_id"], unique=False
    )
    op.drop_constraint(op.f("pessoa_usuario_id_fkey"), "pessoa", type_="foreignkey")
    op.create_foreign_key(
        None, "pessoa", "usuario", ["usuario_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "usuario",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "usuario",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "usuario",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "updated_at")
    op.drop_column("usuario", "created_at")
    op.drop_column("usuario", "is_active")
    op.drop_constraint("pessoa_usuario_id_fkey", "pessoa", type_="foreignkey")
    op.create_foreign_key(
        op.f("pessoa_usuario_id_fkey"), "pessoa", "usuario", ["usuario_id"], ["id"]
    )
    op.drop_index(op.f("ix_pessoa_usuario_id"), table_name="pessoa")
    op.drop_column("pessoa", "updated_at")
    op.drop_column("pessoa", "created_at")
    op.drop_index(op.f("ix_emprestimo_usuario_id"), table_name="emprestimo")
    op.drop_index(op.f("ix_emprestimo_status"), table_name="emprestimo")
    op.drop_index(
        op.f("ix_emprestimo_data_devolucao_esperada"), table_name="emprestimo"
    )
    op.drop_column("emprestimo", "updated_at")
    op.drop_column("emprestimo", "created_at")
    # ### end Alembic commands ###
